#!/bin/bash

go build -o streaming_server ./cmd/bin/streaming_server.go
go build -o streaming_client ./cmd/bin/streaming_client.go

kill -9 `ps aux | grep -w streaming_client | grep -v grep | awk '{print $2}'` &>/dev/null
kill -9 `ps aux | grep -w streaming_server | grep -v grep | awk '{print $2}'` &>/dev/null

sleepDuration=$1
serverCount=$(($2-1))

for i in `seq 0 $serverCount`
do
    ./streaming_server 3000$i $i $2 $sleepDuration &>/dev/null &
    echo "Spawned server on 3000$i"
done
